name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3.5.1

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.0
        with:
          node-version: '18' # Use LTS version or specify a preferred version

      # Install dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v2

      # Build the project
      - name: Build project
        run: npm run build

      # Upload production-ready build files
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Download the artifact produced in the build job
      - name: Download artifact
        uses: actions/download-artifact@v3.1.2
        with:
          name: production-files
          path: ./dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
